### ISSUE TITLE
Right-Clicking on the screen before ever hitting Esc crashes the app on Windows 10

### ISSUE THREAD

**Issue by GalaxyLittlepaws** [ThomasR95/rahituber#1]
**Issue:**
On Windows 10, if you right-click the initial screen then it will crash to desktop. Hitting the Esc key works normally, and then you can right-click just fine. Hitting Esc first will allow you to have no more crashes, even after restarting the app.

**Environment:**
Processor	11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz   2.59 GHz
Installed RAM	32.0 GB (31.9 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Home
Version	22H2
Installed on	‎3/‎13/‎2023
OS build	19045.3208
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**How to reproduce:**
- Start the app
- - You must have never hit Esc to open the menu before
- Right-click on the lavender screen
- The app crashes to desktop

**Crash Info from Windows Event Log:**
```
Faulting application name: RahiTuber.exe, version: 0.0.0.0, time stamp: 0x64cd281c
Faulting module name: RahiTuber.exe, version: 0.0.0.0, time stamp: 0x64cd281c
Exception code: 0xc0000005
Fault offset: 0x00011f43
Faulting process id: 0x2f0c
Faulting application start time: 0x01d9c8178cd0bfa2
Faulting application path: C:\Users\galax\Programs\RahiTuber-2023-08-04c\RahiTuber.exe
Faulting module path: C:\Users\galax\Programs\RahiTuber-2023-08-04c\RahiTuber.exe
Report Id: 72d05748-ed96-4d6c-a499-7b7c941b4a1c
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by ThomasR95** [comment]
Thank you very much for bringing this up, ill investigate when i next get chance tomorrow. Can you explain how you worked out it was first-time only (i.e. did you have to re-extract the game to see it again)? Does deleting the two xml files have the same effect?
Cheers!
Tom

**Comment by GalaxyLittlepaws** [comment]
I had noticed this because I kept trying to open the menu with a right-click and it kept crashing (I attempted this 4 times) until I eventually tried the Esc key instead. Then it stopped crashing on a right-click.

Removing the two XML files created doesn't seem to allow reproducing the crash.

You do have to re-extract the zip in order to reproduce the issue. Copy/pasting an already-extracted folder doesn't work, it has to be a completely fresh copy.

**Comment by ThomasR95** [comment]
Thank you for the help! I'll see what i can find.

**Comment by ThomasR95** [comment]
Hi there, please can you check if my latest changes have solved the issue? https://rahisaurus.itch.io/rahituber/devlog/571553/bugfix-2023-08-07

**Comment by GalaxyLittlepaws** [comment]
Yes, the issue seems to be resolved! Thanks for the quick bugfix. :3
