### ISSUE TITLE
Inconsistent Audio Reaction

### ISSUE THREAD

**Issue by Shasskor** [ThomasR95/rahituber#2]
**Issue:**
On  Windows 11, randomly while talking, my PNGtuber will just go to idle regardless of how loud I am. Looking at the meter below the Talk Threshold setting the audio seems to sporadically cut to zero even while I'm talking, regardless of what level I set the threshold to.
I've compared the Talk Threshold meter with the volume visualizer of an audio software and it cuts out even when that software claims the audio is loud and clear. If I make a loud prolonged "mmm" noise RahiTuber won't react at all.
If I repeatedly say "Yeah" It will sometimes react normally (Remain in talking mode as long as configured with Soft Fall), sometimes go to idle prematurely (Return to idle while I'm still making the noise, or immediately afterwards), or simply not react at all, despite the volume of the "yeah" being akin, or louder than previous times it reacted.
I've tried Adjusting the Soft Fall and every other setting I could find to no avail. I've double-checked that it is using the appropriate microphone, both on RahiTuber and the program I used to compare audio levels.

**Environment:**
Processor: AMD Ryzen 5 5600X 6-Core Processor 3.80GHz
Installed Ram: 32,0 GB (31,9GB usable)
Systemtype: 64-bit operating system, x64-based processor
Edition: Windows 11 Home
Version: 22H2
Installed: 21.12.2022
OS build: 22621.2134
Experience: Windows Feature Experience Pack 1000.22659.1000.0

**Comment by ThomasR95** [comment]
Hi,
Thanks for your comment. This is likely due to the rudimentary audio filtering i have added to help counteract keyboard and mouse noise. 
I'll add an option to disable the filtering now.
Cheers
Tom

**Comment by ThomasR95** [comment]
Hi, please check the latest update: https://rahisaurus.itch.io/rahituber/devlog/581140/update-2023-08-28
and let me know if this solves your problem!
Cheers
Tom

**Comment by Shasskor** [comment]
Marvelous! It works just fine now, thanks!
